### PR TITLE
Update location of pendo agent

### PR DESCRIPTION
**Pull request by mdellanoce**
Is there a good way to try this out on a test application with a real analytics.js?

### CODE REVIEW

**Comment by evorick** [comment]
@ndhoule Could we possibly get this pulled into the integration?

**Comment by hankim813** [comment]
@mdellanoce unfortunately, only segment engineers can test this on staging :/

I can merge this and deploy this next Monday (can't deploy on fridays) if there are no breaking changes by upgrading the script here.

**Comment by evorick** [comment]
@hankim813 Any update on this?

**Comment by hankim813** [comment]
@evorick still waiting for @mdellanoce or someone from pendo to confirm my question:

>  if there are no breaking changes by upgrading the script here.

If you can assure that all existing methods do not need to be updated, I can deploy this today. Thanks!

**Comment by evorick** [comment]
Thanks @hankim813. @mdellanoce ^

**Comment by mdellanoce** [comment]
@hankim813 there are no breaking changes, the only change is the location that we load the pendo script from

**Comment by hankim813** [comment]
@mdellanoce awesome! Could you also push a release commit on this branch? 

1) bump `package.json`'s minor version
2) update `HISTORY.md` following existing convention 
3) `git commit -m 'Release x.x.x'`

Then we'll take it from there! :)

**Comment by mdellanoce** [comment]
@hankim813 done

**Comment by hankim813** [comment]
@mdellanoce yeah so looks like aws is down right now 😅  will try to get to this when that is resolved so I can run some tests.

**Comment by evorick** [comment]
@hankim813 Could we try again today for this?

**Review by anoonan — APPROVED** [review]

**Comment by anoonan** [comment]
hey @evorick, I'll deploy this today and follow up when it's complete.

**Comment by anoonan** [comment]
hey @evorick and @mdellanoce, this has been deployed!

**Comment by evorick** [comment]
@anoonan Great! Thanks!

**Pull request merged**
