### PR TITLE
Fixed the representation of the Segment Anonymous ID

### PR DESCRIPTION
**Pull request by brec-c**
We need to make sure the anonymous id that segment generates gets added the constant value of "_PENDO_T_" to the front of the id.

### CODE REVIEW

**Comment by brec-c** [comment]
@mdellanoce get in here

**Comment by mdellanoce** [comment]
👍 lgtm

**Review by mdellanoce — APPROVED** [review]

**Comment by brec-c** [comment]
Is anyone at segment reading these? We need to get access to manage our integration.

**Comment by CarlosMecha** [comment]
Hi @brec-c , could we add tests? It help us to prevent regressions. Thanks!

**Review by CarlosMecha — APPROVED** [review]
Approved despite there are not tests provided. We'll add them before the release.

**Pull request merged**
